[package]
name = "snake_bevy"
version = "0.1.0"
authors = ["mtKeller <micah.t.keller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.3.0"